name: Create webapp release
on:
  workflow_call:
    inputs:
      env_webapp_version:
        required: true
        type: string
      env_webapp_branch:
        required: false
        type: string
        default: main
jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: create release for webapp
        run: |
            curl -L --fail-with-body \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.APP_AUTO_RELEASE }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/FLECS-Technologies/flecs-webapp-dummy/releases \
            -d '{"tag_name":"${{ inputs.env_webapp_version }}","name":"${{ inputs.env_webapp_version }}","body":"Automated dummy release","target_commitish": "${{ inputs.env_webapp_branch }}","draft":false,"prerelease":false,"generate_release_notes":true}'

