name: Release
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Fake build job
       run: echo "This is just a test for webapp dummy"
  build_and_special:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Fake build job two
        run: echo "This is just a test for webapp dummy"
